'use strict';
// @flow

// The following table comes from <http://www.unicode.org/Public/9.0.0/ucd/Blocks.txt>.
// Keep it synchronized with <http://www.unicode.org/Public/UCD/latest/ucd/Blocks.txt>.

module.exports = {
    // 'Basic Latin': (char: number) => char >= 0x0000 && char <= 0x007F,
    'Latin-1 Supplement': (char: number) => char >= 0x0080 && char <= 0x00FF,
    // 'Latin Extended-A': (char: number) => char >= 0x0100 && char <= 0x017F,
    // 'Latin Extended-B': (char: number) => char >= 0x0180 && char <= 0x024F,
    // 'IPA Extensions': (char: number) => char >= 0x0250 && char <= 0x02AF,
    // 'Spacing Modifier Letters': (char: number) => char >= 0x02B0 && char <= 0x02FF,
    // 'Combining Diacritical Marks': (char: number) => char >= 0x0300 && char <= 0x036F,
    // 'Greek and Coptic': (char: number) => char >= 0x0370 && char <= 0x03FF,
    // 'Cyrillic': (char: number) => char >= 0x0400 && char <= 0x04FF,
    // 'Cyrillic Supplement': (char: number) => char >= 0x0500 && char <= 0x052F,
    // 'Armenian': (char: number) => char >= 0x0530 && char <= 0x058F,
    // 'Hebrew': (char: number) => char >= 0x0590 && char <= 0x05FF,
    // 'Arabic': (char: number) => char >= 0x0600 && char <= 0x06FF,
    // 'Syriac': (char: number) => char >= 0x0700 && char <= 0x074F,
    // 'Arabic Supplement': (char: number) => char >= 0x0750 && char <= 0x077F,
    // 'Thaana': (char: number) => char >= 0x0780 && char <= 0x07BF,
    // 'NKo': (char: number) => char >= 0x07C0 && char <= 0x07FF,
    // 'Samaritan': (char: number) => char >= 0x0800 && char <= 0x083F,
    // 'Mandaic': (char: number) => char >= 0x0840 && char <= 0x085F,
    // 'Arabic Extended-A': (char: number) => char >= 0x08A0 && char <= 0x08FF,
    // 'Devanagari': (char: number) => char >= 0x0900 && char <= 0x097F,
    // 'Bengali': (char: number) => char >= 0x0980 && char <= 0x09FF,
    // 'Gurmukhi': (char: number) => char >= 0x0A00 && char <= 0x0A7F,
    // 'Gujarati': (char: number) => char >= 0x0A80 && char <= 0x0AFF,
    // 'Oriya': (char: number) => char >= 0x0B00 && char <= 0x0B7F,
    // 'Tamil': (char: number) => char >= 0x0B80 && char <= 0x0BFF,
    // 'Telugu': (char: number) => char >= 0x0C00 && char <= 0x0C7F,
    // 'Kannada': (char: number) => char >= 0x0C80 && char <= 0x0CFF,
    // 'Malayalam': (char: number) => char >= 0x0D00 && char <= 0x0D7F,
    // 'Sinhala': (char: number) => char >= 0x0D80 && char <= 0x0DFF,
    // 'Thai': (char: number) => char >= 0x0E00 && char <= 0x0E7F,
    // 'Lao': (char: number) => char >= 0x0E80 && char <= 0x0EFF,
    // 'Tibetan': (char: number) => char >= 0x0F00 && char <= 0x0FFF,
    // 'Myanmar': (char: number) => char >= 0x1000 && char <= 0x109F,
    // 'Georgian': (char: number) => char >= 0x10A0 && char <= 0x10FF,
    'Hangul Jamo': (char: number) => char >= 0x1100 && char <= 0x11FF,
    // 'Ethiopic': (char: number) => char >= 0x1200 && char <= 0x137F,
    // 'Ethiopic Supplement': (char: number) => char >= 0x1380 && char <= 0x139F,
    // 'Cherokee': (char: number) => char >= 0x13A0 && char <= 0x13FF,
    'Unified Canadian Aboriginal Syllabics': (char: number) => char >= 0x1400 && char <= 0x167F,
    // 'Ogham': (char: number) => char >= 0x1680 && char <= 0x169F,
    // 'Runic': (char: number) => char >= 0x16A0 && char <= 0x16FF,
    // 'Tagalog': (char: number) => char >= 0x1700 && char <= 0x171F,
    // 'Hanunoo': (char: number) => char >= 0x1720 && char <= 0x173F,
    // 'Buhid': (char: number) => char >= 0x1740 && char <= 0x175F,
    // 'Tagbanwa': (char: number) => char >= 0x1760 && char <= 0x177F,
    // 'Khmer': (char: number) => char >= 0x1780 && char <= 0x17FF,
    // 'Mongolian': (char: number) => char >= 0x1800 && char <= 0x18AF,
    'Unified Canadian Aboriginal Syllabics Extended': (char: number) => char >= 0x18B0 && char <= 0x18FF,
    // 'Limbu': (char: number) => char >= 0x1900 && char <= 0x194F,
    // 'Tai Le': (char: number) => char >= 0x1950 && char <= 0x197F,
    // 'New Tai Lue': (char: number) => char >= 0x1980 && char <= 0x19DF,
    // 'Khmer Symbols': (char: number) => char >= 0x19E0 && char <= 0x19FF,
    // 'Buginese': (char: number) => char >= 0x1A00 && char <= 0x1A1F,
    // 'Tai Tham': (char: number) => char >= 0x1A20 && char <= 0x1AAF,
    // 'Combining Diacritical Marks Extended': (char: number) => char >= 0x1AB0 && char <= 0x1AFF,
    // 'Balinese': (char: number) => char >= 0x1B00 && char <= 0x1B7F,
    // 'Sundanese': (char: number) => char >= 0x1B80 && char <= 0x1BBF,
    // 'Batak': (char: number) => char >= 0x1BC0 && char <= 0x1BFF,
    // 'Lepcha': (char: number) => char >= 0x1C00 && char <= 0x1C4F,
    // 'Ol Chiki': (char: number) => char >= 0x1C50 && char <= 0x1C7F,
    // 'Cyrillic Extended-C': (char: number) => char >= 0x1C80 && char <= 0x1C8F,
    // 'Sundanese Supplement': (char: number) => char >= 0x1CC0 && char <= 0x1CCF,
    // 'Vedic Extensions': (char: number) => char >= 0x1CD0 && char <= 0x1CFF,
    // 'Phonetic Extensions': (char: number) => char >= 0x1D00 && char <= 0x1D7F,
    // 'Phonetic Extensions Supplement': (char: number) => char >= 0x1D80 && char <= 0x1DBF,
    // 'Combining Diacritical Marks Supplement': (char: number) => char >= 0x1DC0 && char <= 0x1DFF,
    // 'Latin Extended Additional': (char: number) => char >= 0x1E00 && char <= 0x1EFF,
    // 'Greek Extended': (char: number) => char >= 0x1F00 && char <= 0x1FFF,
    'General Punctuation': (char: number) => char >= 0x2000 && char <= 0x206F,
    // 'Superscripts and Subscripts': (char: number) => char >= 0x2070 && char <= 0x209F,
    // 'Currency Symbols': (char: number) => char >= 0x20A0 && char <= 0x20CF,
    // 'Combining Diacritical Marks for Symbols': (char: number) => char >= 0x20D0 && char <= 0x20FF,
    'Letterlike Symbols': (char: number) => char >= 0x2100 && char <= 0x214F,
    'Number Forms': (char: number) => char >= 0x2150 && char <= 0x218F,
    // 'Arrows': (char: number) => char >= 0x2190 && char <= 0x21FF,
    // 'Mathematical Operators': (char: number) => char >= 0x2200 && char <= 0x22FF,
    'Miscellaneous Technical': (char: number) => char >= 0x2300 && char <= 0x23FF,
    'Control Pictures': (char: number) => char >= 0x2400 && char <= 0x243F,
    'Optical Character Recognition': (char: number) => char >= 0x2440 && char <= 0x245F,
    'Enclosed Alphanumerics': (char: number) => char >= 0x2460 && char <= 0x24FF,
    // 'Box Drawing': (char: number) => char >= 0x2500 && char <= 0x257F,
    // 'Block Elements': (char: number) => char >= 0x2580 && char <= 0x259F,
    'Geometric Shapes': (char: number) => char >= 0x25A0 && char <= 0x25FF,
    'Miscellaneous Symbols': (char: number) => char >= 0x2600 && char <= 0x26FF,
    // 'Dingbats': (char: number) => char >= 0x2700 && char <= 0x27BF,
    // 'Miscellaneous Mathematical Symbols-A': (char: number) => char >= 0x27C0 && char <= 0x27EF,
    // 'Supplemental Arrows-A': (char: number) => char >= 0x27F0 && char <= 0x27FF,
    // 'Braille Patterns': (char: number) => char >= 0x2800 && char <= 0x28FF,
    // 'Supplemental Arrows-B': (char: number) => char >= 0x2900 && char <= 0x297F,
    // 'Miscellaneous Mathematical Symbols-B': (char: number) => char >= 0x2980 && char <= 0x29FF,
    // 'Supplemental Mathematical Operators': (char: number) => char >= 0x2A00 && char <= 0x2AFF,
    'Miscellaneous Symbols and Arrows': (char: number) => char >= 0x2B00 && char <= 0x2BFF,
    // 'Glagolitic': (char: number) => char >= 0x2C00 && char <= 0x2C5F,
    // 'Latin Extended-C': (char: number) => char >= 0x2C60 && char <= 0x2C7F,
    // 'Coptic': (char: number) => char >= 0x2C80 && char <= 0x2CFF,
    // 'Georgian Supplement': (char: number) => char >= 0x2D00 && char <= 0x2D2F,
    // 'Tifinagh': (char: number) => char >= 0x2D30 && char <= 0x2D7F,
    // 'Ethiopic Extended': (char: number) => char >= 0x2D80 && char <= 0x2DDF,
    // 'Cyrillic Extended-A': (char: number) => char >= 0x2DE0 && char <= 0x2DFF,
    // 'Supplemental Punctuation': (char: number) => char >= 0x2E00 && char <= 0x2E7F,
    'CJK Radicals Supplement': (char: number) => char >= 0x2E80 && char <= 0x2EFF,
    'Kangxi Radicals': (char: number) => char >= 0x2F00 && char <= 0x2FDF,
    'Ideographic Description Characters': (char: number) => char >= 0x2FF0 && char <= 0x2FFF,
    'CJK Symbols and Punctuation': (char: number) => char >= 0x3000 && char <= 0x303F,
    'Hiragana': (char: number) => char >= 0x3040 && char <= 0x309F,
    'Katakana': (char: number) => char >= 0x30A0 && char <= 0x30FF,
    'Bopomofo': (char: number) => char >= 0x3100 && char <= 0x312F,
    'Hangul Compatibility Jamo': (char: number) => char >= 0x3130 && char <= 0x318F,
    'Kanbun': (char: number) => char >= 0x3190 && char <= 0x319F,
    'Bopomofo Extended': (char: number) => char >= 0x31A0 && char <= 0x31BF,
    'CJK Strokes': (char: number) => char >= 0x31C0 && char <= 0x31EF,
    'Katakana Phonetic Extensions': (char: number) => char >= 0x31F0 && char <= 0x31FF,
    'Enclosed CJK Letters and Months': (char: number) => char >= 0x3200 && char <= 0x32FF,
    'CJK Compatibility': (char: number) => char >= 0x3300 && char <= 0x33FF,
    'CJK Unified Ideographs Extension A': (char: number) => char >= 0x3400 && char <= 0x4DBF,
    'Yijing Hexagram Symbols': (char: number) => char >= 0x4DC0 && char <= 0x4DFF,
    'CJK Unified Ideographs': (char: number) => char >= 0x4E00 && char <= 0x9FFF,
    'Yi Syllables': (char: number) => char >= 0xA000 && char <= 0xA48F,
    'Yi Radicals': (char: number) => char >= 0xA490 && char <= 0xA4CF,
    // 'Lisu': (char: number) => char >= 0xA4D0 && char <= 0xA4FF,
    // 'Vai': (char: number) => char >= 0xA500 && char <= 0xA63F,
    // 'Cyrillic Extended-B': (char: number) => char >= 0xA640 && char <= 0xA69F,
    // 'Bamum': (char: number) => char >= 0xA6A0 && char <= 0xA6FF,
    // 'Modifier Tone Letters': (char: number) => char >= 0xA700 && char <= 0xA71F,
    // 'Latin Extended-D': (char: number) => char >= 0xA720 && char <= 0xA7FF,
    // 'Syloti Nagri': (char: number) => char >= 0xA800 && char <= 0xA82F,
    // 'Common Indic Number Forms': (char: number) => char >= 0xA830 && char <= 0xA83F,
    // 'Phags-pa': (char: number) => char >= 0xA840 && char <= 0xA87F,
    // 'Saurashtra': (char: number) => char >= 0xA880 && char <= 0xA8DF,
    // 'Devanagari Extended': (char: number) => char >= 0xA8E0 && char <= 0xA8FF,
    // 'Kayah Li': (char: number) => char >= 0xA900 && char <= 0xA92F,
    // 'Rejang': (char: number) => char >= 0xA930 && char <= 0xA95F,
    'Hangul Jamo Extended-A': (char: number) => char >= 0xA960 && char <= 0xA97F,
    // 'Javanese': (char: number) => char >= 0xA980 && char <= 0xA9DF,
    // 'Myanmar Extended-B': (char: number) => char >= 0xA9E0 && char <= 0xA9FF,
    // 'Cham': (char: number) => char >= 0xAA00 && char <= 0xAA5F,
    // 'Myanmar Extended-A': (char: number) => char >= 0xAA60 && char <= 0xAA7F,
    // 'Tai Viet': (char: number) => char >= 0xAA80 && char <= 0xAADF,
    // 'Meetei Mayek Extensions': (char: number) => char >= 0xAAE0 && char <= 0xAAFF,
    // 'Ethiopic Extended-A': (char: number) => char >= 0xAB00 && char <= 0xAB2F,
    // 'Latin Extended-E': (char: number) => char >= 0xAB30 && char <= 0xAB6F,
    // 'Cherokee Supplement': (char: number) => char >= 0xAB70 && char <= 0xABBF,
    // 'Meetei Mayek': (char: number) => char >= 0xABC0 && char <= 0xABFF,
    'Hangul Syllables': (char: number) => char >= 0xAC00 && char <= 0xD7AF,
    'Hangul Jamo Extended-B': (char: number) => char >= 0xD7B0 && char <= 0xD7FF,
    // 'High Surrogates': (char: number) => char >= 0xD800 && char <= 0xDB7F,
    // 'High Private Use Surrogates': (char: number) => char >= 0xDB80 && char <= 0xDBFF,
    // 'Low Surrogates': (char: number) => char >= 0xDC00 && char <= 0xDFFF,
    'Private Use Area': (char: number) => char >= 0xE000 && char <= 0xF8FF,
    'CJK Compatibility Ideographs': (char: number) => char >= 0xF900 && char <= 0xFAFF,
    // 'Alphabetic Presentation Forms': (char: number) => char >= 0xFB00 && char <= 0xFB4F,
    // 'Arabic Presentation Forms-A': (char: number) => char >= 0xFB50 && char <= 0xFDFF,
    // 'Variation Selectors': (char: number) => char >= 0xFE00 && char <= 0xFE0F,
    'Vertical Forms': (char: number) => char >= 0xFE10 && char <= 0xFE1F,
    // 'Combining Half Marks': (char: number) => char >= 0xFE20 && char <= 0xFE2F,
    'CJK Compatibility Forms': (char: number) => char >= 0xFE30 && char <= 0xFE4F,
    'Small Form Variants': (char: number) => char >= 0xFE50 && char <= 0xFE6F,
    // 'Arabic Presentation Forms-B': (char: number) => char >= 0xFE70 && char <= 0xFEFF,
    'Halfwidth and Fullwidth Forms': (char: number) => char >= 0xFF00 && char <= 0xFFEF
    // 'Specials': (char: number) => char >= 0xFFF0 && char <= 0xFFFF,
    // 'Linear B Syllabary': (char: number) => char >= 0x10000 && char <= 0x1007F,
    // 'Linear B Ideograms': (char: number) => char >= 0x10080 && char <= 0x100FF,
    // 'Aegean Numbers': (char: number) => char >= 0x10100 && char <= 0x1013F,
    // 'Ancient Greek Numbers': (char: number) => char >= 0x10140 && char <= 0x1018F,
    // 'Ancient Symbols': (char: number) => char >= 0x10190 && char <= 0x101CF,
    // 'Phaistos Disc': (char: number) => char >= 0x101D0 && char <= 0x101FF,
    // 'Lycian': (char: number) => char >= 0x10280 && char <= 0x1029F,
    // 'Carian': (char: number) => char >= 0x102A0 && char <= 0x102DF,
    // 'Coptic Epact Numbers': (char: number) => char >= 0x102E0 && char <= 0x102FF,
    // 'Old Italic': (char: number) => char >= 0x10300 && char <= 0x1032F,
    // 'Gothic': (char: number) => char >= 0x10330 && char <= 0x1034F,
    // 'Old Permic': (char: number) => char >= 0x10350 && char <= 0x1037F,
    // 'Ugaritic': (char: number) => char >= 0x10380 && char <= 0x1039F,
    // 'Old Persian': (char: number) => char >= 0x103A0 && char <= 0x103DF,
    // 'Deseret': (char: number) => char >= 0x10400 && char <= 0x1044F,
    // 'Shavian': (char: number) => char >= 0x10450 && char <= 0x1047F,
    // 'Osmanya': (char: number) => char >= 0x10480 && char <= 0x104AF,
    // 'Osage': (char: number) => char >= 0x104B0 && char <= 0x104FF,
    // 'Elbasan': (char: number) => char >= 0x10500 && char <= 0x1052F,
    // 'Caucasian Albanian': (char: number) => char >= 0x10530 && char <= 0x1056F,
    // 'Linear A': (char: number) => char >= 0x10600 && char <= 0x1077F,
    // 'Cypriot Syllabary': (char: number) => char >= 0x10800 && char <= 0x1083F,
    // 'Imperial Aramaic': (char: number) => char >= 0x10840 && char <= 0x1085F,
    // 'Palmyrene': (char: number) => char >= 0x10860 && char <= 0x1087F,
    // 'Nabataean': (char: number) => char >= 0x10880 && char <= 0x108AF,
    // 'Hatran': (char: number) => char >= 0x108E0 && char <= 0x108FF,
    // 'Phoenician': (char: number) => char >= 0x10900 && char <= 0x1091F,
    // 'Lydian': (char: number) => char >= 0x10920 && char <= 0x1093F,
    // 'Meroitic Hieroglyphs': (char: number) => char >= 0x10980 && char <= 0x1099F,
    // 'Meroitic Cursive': (char: number) => char >= 0x109A0 && char <= 0x109FF,
    // 'Kharoshthi': (char: number) => char >= 0x10A00 && char <= 0x10A5F,
    // 'Old South Arabian': (char: number) => char >= 0x10A60 && char <= 0x10A7F,
    // 'Old North Arabian': (char: number) => char >= 0x10A80 && char <= 0x10A9F,
    // 'Manichaean': (char: number) => char >= 0x10AC0 && char <= 0x10AFF,
    // 'Avestan': (char: number) => char >= 0x10B00 && char <= 0x10B3F,
    // 'Inscriptional Parthian': (char: number) => char >= 0x10B40 && char <= 0x10B5F,
    // 'Inscriptional Pahlavi': (char: number) => char >= 0x10B60 && char <= 0x10B7F,
    // 'Psalter Pahlavi': (char: number) => char >= 0x10B80 && char <= 0x10BAF,
    // 'Old Turkic': (char: number) => char >= 0x10C00 && char <= 0x10C4F,
    // 'Old Hungarian': (char: number) => char >= 0x10C80 && char <= 0x10CFF,
    // 'Rumi Numeral Symbols': (char: number) => char >= 0x10E60 && char <= 0x10E7F,
    // 'Brahmi': (char: number) => char >= 0x11000 && char <= 0x1107F,
    // 'Kaithi': (char: number) => char >= 0x11080 && char <= 0x110CF,
    // 'Sora Sompeng': (char: number) => char >= 0x110D0 && char <= 0x110FF,
    // 'Chakma': (char: number) => char >= 0x11100 && char <= 0x1114F,
    // 'Mahajani': (char: number) => char >= 0x11150 && char <= 0x1117F,
    // 'Sharada': (char: number) => char >= 0x11180 && char <= 0x111DF,
    // 'Sinhala Archaic Numbers': (char: number) => char >= 0x111E0 && char <= 0x111FF,
    // 'Khojki': (char: number) => char >= 0x11200 && char <= 0x1124F,
    // 'Multani': (char: number) => char >= 0x11280 && char <= 0x112AF,
    // 'Khudawadi': (char: number) => char >= 0x112B0 && char <= 0x112FF,
    // 'Grantha': (char: number) => char >= 0x11300 && char <= 0x1137F,
    // 'Newa': (char: number) => char >= 0x11400 && char <= 0x1147F,
    // 'Tirhuta': (char: number) => char >= 0x11480 && char <= 0x114DF,
    // 'Siddham': (char: number) => char >= 0x11580 && char <= 0x115FF,
    // 'Modi': (char: number) => char >= 0x11600 && char <= 0x1165F,
    // 'Mongolian Supplement': (char: number) => char >= 0x11660 && char <= 0x1167F,
    // 'Takri': (char: number) => char >= 0x11680 && char <= 0x116CF,
    // 'Ahom': (char: number) => char >= 0x11700 && char <= 0x1173F,
    // 'Warang Citi': (char: number) => char >= 0x118A0 && char <= 0x118FF,
    // 'Pau Cin Hau': (char: number) => char >= 0x11AC0 && char <= 0x11AFF,
    // 'Bhaiksuki': (char: number) => char >= 0x11C00 && char <= 0x11C6F,
    // 'Marchen': (char: number) => char >= 0x11C70 && char <= 0x11CBF,
    // 'Cuneiform': (char: number) => char >= 0x12000 && char <= 0x123FF,
    // 'Cuneiform Numbers and Punctuation': (char: number) => char >= 0x12400 && char <= 0x1247F,
    // 'Early Dynastic Cuneiform': (char: number) => char >= 0x12480 && char <= 0x1254F,
    // 'Egyptian Hieroglyphs': (char: number) => char >= 0x13000 && char <= 0x1342F,
    // 'Anatolian Hieroglyphs': (char: number) => char >= 0x14400 && char <= 0x1467F,
    // 'Bamum Supplement': (char: number) => char >= 0x16800 && char <= 0x16A3F,
    // 'Mro': (char: number) => char >= 0x16A40 && char <= 0x16A6F,
    // 'Bassa Vah': (char: number) => char >= 0x16AD0 && char <= 0x16AFF,
    // 'Pahawh Hmong': (char: number) => char >= 0x16B00 && char <= 0x16B8F,
    // 'Miao': (char: number) => char >= 0x16F00 && char <= 0x16F9F,
    // 'Ideographic Symbols and Punctuation': (char: number) => char >= 0x16FE0 && char <= 0x16FFF,
    // 'Tangut': (char: number) => char >= 0x17000 && char <= 0x187FF,
    // 'Tangut Components': (char: number) => char >= 0x18800 && char <= 0x18AFF,
    // 'Kana Supplement': (char: number) => char >= 0x1B000 && char <= 0x1B0FF,
    // 'Duployan': (char: number) => char >= 0x1BC00 && char <= 0x1BC9F,
    // 'Shorthand Format Controls': (char: number) => char >= 0x1BCA0 && char <= 0x1BCAF,
    // 'Byzantine Musical Symbols': (char: number) => char >= 0x1D000 && char <= 0x1D0FF,
    // 'Musical Symbols': (char: number) => char >= 0x1D100 && char <= 0x1D1FF,
    // 'Ancient Greek Musical Notation': (char: number) => char >= 0x1D200 && char <= 0x1D24F,
    // 'Tai Xuan Jing Symbols': (char: number) => char >= 0x1D300 && char <= 0x1D35F,
    // 'Counting Rod Numerals': (char: number) => char >= 0x1D360 && char <= 0x1D37F,
    // 'Mathematical Alphanumeric Symbols': (char: number) => char >= 0x1D400 && char <= 0x1D7FF,
    // 'Sutton SignWriting': (char: number) => char >= 0x1D800 && char <= 0x1DAAF,
    // 'Glagolitic Supplement': (char: number) => char >= 0x1E000 && char <= 0x1E02F,
    // 'Mende Kikakui': (char: number) => char >= 0x1E800 && char <= 0x1E8DF,
    // 'Adlam': (char: number) => char >= 0x1E900 && char <= 0x1E95F,
    // 'Arabic Mathematical Alphabetic Symbols': (char: number) => char >= 0x1EE00 && char <= 0x1EEFF,
    // 'Mahjong Tiles': (char: number) => char >= 0x1F000 && char <= 0x1F02F,
    // 'Domino Tiles': (char: number) => char >= 0x1F030 && char <= 0x1F09F,
    // 'Playing Cards': (char: number) => char >= 0x1F0A0 && char <= 0x1F0FF,
    // 'Enclosed Alphanumeric Supplement': (char: number) => char >= 0x1F100 && char <= 0x1F1FF,
    // 'Enclosed Ideographic Supplement': (char: number) => char >= 0x1F200 && char <= 0x1F2FF,
    // 'Miscellaneous Symbols and Pictographs': (char: number) => char >= 0x1F300 && char <= 0x1F5FF,
    // 'Emoticons': (char: number) => char >= 0x1F600 && char <= 0x1F64F,
    // 'Ornamental Dingbats': (char: number) => char >= 0x1F650 && char <= 0x1F67F,
    // 'Transport and Map Symbols': (char: number) => char >= 0x1F680 && char <= 0x1F6FF,
    // 'Alchemical Symbols': (char: number) => char >= 0x1F700 && char <= 0x1F77F,
    // 'Geometric Shapes Extended': (char: number) => char >= 0x1F780 && char <= 0x1F7FF,
    // 'Supplemental Arrows-C': (char: number) => char >= 0x1F800 && char <= 0x1F8FF,
    // 'Supplemental Symbols and Pictographs': (char: number) => char >= 0x1F900 && char <= 0x1F9FF,
    // 'CJK Unified Ideographs Extension B': (char: number) => char >= 0x20000 && char <= 0x2A6DF,
    // 'CJK Unified Ideographs Extension C': (char: number) => char >= 0x2A700 && char <= 0x2B73F,
    // 'CJK Unified Ideographs Extension D': (char: number) => char >= 0x2B740 && char <= 0x2B81F,
    // 'CJK Unified Ideographs Extension E': (char: number) => char >= 0x2B820 && char <= 0x2CEAF,
    // 'CJK Compatibility Ideographs Supplement': (char: number) => char >= 0x2F800 && char <= 0x2FA1F,
    // 'Tags': (char: number) => char >= 0xE0000 && char <= 0xE007F,
    // 'Variation Selectors Supplement': (char: number) => char >= 0xE0100 && char <= 0xE01EF,
    // 'Supplementary Private Use Area-A': (char: number) => char >= 0xF0000 && char <= 0xFFFFF,
    // 'Supplementary Private Use Area-B': (char: number) => char >= 0x100000 && char <= 0x10FFFF,
};
